### ISSUE TITLE
New Duprs Domain

### ISSUE THREAD

**Issue by Echological** [Echological/Duprs-Revival#7]
Comment below any domain names you would like to see be used for Duprs

Current domain: `duprs.com`

Should we change this? (yes/no)

If yes, what should we change it to? 

Reply with the comments below 👇

**Comment by ZGSD** [comment]
does durps stand for deez.users.play.really.sus

**Comment by Rimbly** [comment]
Nah don't change it, keep it simple like the old days.

**Comment by Echological** [comment]
> Nah don't change it, keep it simple like the old days.

So, to clarify, keep it as `duprs.com`?

**Comment by Echological** [comment]
this will stay as `duprs.com` for now
